//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_employees
    {
        public int peid { get; set; }
        public Nullable<int> project_pid { get; set; }
        public Nullable<int> employee_eid { get; set; }
    
        public  employee employee { get; set; }
        public  project project { get; set; }
    }
}
