//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.projects = new HashSet<project>();
            this.project_costs = new HashSet<project_costs>();
            this.project_employees = new HashSet<project_employees>();
            this.project_hours = new HashSet<project_hours>();
            this.project_messages = new HashSet<project_messages>();
        }
    
        public int eid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string homeaddress { get; set; }
        public Nullable<int> zip { get; set; }
        public string phone { get; set; }
        public string profession { get; set; }
        public string imgname { get; set; }
        public byte[] img { get; set; }
        public Nullable<int> userrole_urid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string kt { get; set; }
        public Nullable<System.DateTime> employeetimestamp { get; set; }
    
        public virtual userrole userrole { get; set; }
        public virtual zipcode zipcode { get; set; }
        public virtual ICollection<project> projects { get; set; }
        public virtual ICollection<project_costs> project_costs { get; set; }
        public virtual ICollection<project_employees> project_employees { get; set; }
        public virtual ICollection<project_hours> project_hours { get; set; }
        public virtual ICollection<project_messages> project_messages { get; set; }
    }
}
