//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.project_costs = new HashSet<project_costs>();
            this.project_employees = new HashSet<project_employees>();
            this.project_hours = new HashSet<project_hours>();
            this.project_messages = new HashSet<project_messages>();
        }
    
        public int pid { get; set; }
        public string projectname { get; set; }
        public Nullable<int> employee_eid { get; set; }
        public string pdescription { get; set; }
        public Nullable<System.DateTime> pdate { get; set; }
        public Nullable<System.DateTime> pdeadline { get; set; }
        public bool projectisfinished { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ICollection<project_costs> project_costs { get; set; }
        public virtual ICollection<project_employees> project_employees { get; set; }
        public virtual ICollection<project_hours> project_hours { get; set; }
        public virtual ICollection<project_messages> project_messages { get; set; }
    }
}
