//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class userrole
    {
        public userrole()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int urid { get; set; }
        public string userrole1 { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
    }
}
